In [47]:
import os
import argparse
import numpy as np
from scipy.interpolate import interp1d
import sys
import pathlib
import csv
import shutil
import ast


In [99]:
runs = ["checkerboard"] + [str(i) for i in range(5, 6)]

In [100]:
for run in runs:
    runPath = pathlib.Path(f"../data/20241011_phantom_mono/Recordings/run_{run}")
    runPath.absolute().resolve()
    runDataFileNames = os.listdir(runPath)
    ndiFiles = [runPath/f for f in runDataFileNames if f.startswith("ndi") and f.endswith(".csv") and not f.endswith("original.csv")]
    videoTimestampFiles = [runPath/f for f in runDataFileNames if f.startswith("endoscope_timestamp_") and f.endswith(".csv") and not f.endswith("original.csv")]
    
    for ndiFile in ndiFiles:
        shutil.copy(str(ndiFile), runPath / (str(ndiFile).split("/")[-1].split(".csv")[0] + "original.csv"))
    break

In [101]:
np.loadtxt(str(videoTimestampFiles[0]), delimiter=",").shape

(2447, 2)

In [102]:
with open(ndiFiles[0], 'r', newline='') as csvfile:
    reader = csv.reader(csvfile, delimiter=',', quotechar='"')
    dataReadList = []
    timeStamps = [] 
    transforms = []
    for row in reader:
        rowRead = []
        for element in row:    
            # elementCleaned = element.replace("array", "").replace("(", "").replace(")", "").replace("nan", "float('nan')").replace("\n", "")
            elementCleaned = element.replace("array(", "").replace(")", "").replace("[", "").replace("]", "").replace("\n", "")
            dataElement = np.fromstring(elementCleaned, sep=",")
            if dataElement.shape[0] == 32:
                dataElement = dataElement.reshape([2, 4, 4])
            rowRead.append(dataElement)
        timeStamps.append(rowRead[1])
        dataReadList.append(rowRead)
        transforms.append(rowRead[3])
    timeStamps = np.array(timeStamps)
    transforms = np.array(transforms)
# np.loadtxt(str(ndiFiles[0]), delimiter=",")

In [98]:
a = np.random.random([4, 2, 3])
print(a)
print(a.reshape([2, -1]))

[[[0.66711592 0.28863613 0.34935601]
  [0.20816637 0.63441899 0.83285774]]

 [[0.42390507 0.26086954 0.26879518]
  [0.22238231 0.4264774  0.46872838]]

 [[0.09860601 0.58722182 0.13978506]
  [0.73700045 0.76899224 0.42910132]]

 [[0.41461259 0.09592565 0.71322484]
  [0.89631956 0.14259707 0.94441184]]]
[[0.66711592 0.28863613 0.34935601 0.20816637 0.63441899 0.83285774
  0.42390507 0.26086954 0.26879518 0.22238231 0.4264774  0.46872838]
 [0.09860601 0.58722182 0.13978506 0.73700045 0.76899224 0.42910132
  0.41461259 0.09592565 0.71322484 0.89631956 0.14259707 0.94441184]]


In [90]:
np.concatenate([a[:3, 3], b])

array([1., 1., 1., 1., 1., 1., 1.])